// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AI_Buddy.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAI_BuddyPackageCmdSetString = "f3ae7c69-4f62-438d-a386-a11549044a8c";
        public static Guid guidAI_BuddyPackageCmdSet = new Guid(guidAI_BuddyPackageCmdSetString);

        public const string guidAI_BuddyPackageString = "2f259d1a-ec99-4bc7-bc55-f1540b114913";
        public static Guid guidAI_BuddyPackage = new Guid(guidAI_BuddyPackageString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int PromptDeepMenu = 0x1023;
        public const int PromptDeepSubmenuGroup = 0x1024;
        public const int PromptDeepSubItem1 = 0x0103;
        public const int ToolsMenuGroup = 0x1021;
        public const int EditorContextMenuGroup = 0x1022;
        public const int MainMenuCmdId = 0x0100;
        public const int PromptDeepSubItem2 = 0x0102;
        public const int cmdidPromptDeepAnalyze = 0x0103;
        public const int cmdidPromptDeepSuggest = 0x0104;
    }
}